# Application Name
spring.application.name=blog

# Import the .env file
spring.config.import=file:.env[.properties]

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.database-platform=${JPA_DATABASE_PLATFORM}

# Thymeleaf Settings
spring.thymeleaf.cache=${THYMELEAF_CACHE}

# Spring Security
spring.security.user.name=${SPRING_SECURITY_USERNAME}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}

# File Upload Directory
app.upload.dir=${UPLOAD_DIR}

# Mail Configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE}
